Added JUNIT report to queue_tdd.yml

diff --git a/.github/workflows/queue_tdd.yml b/.github/workflows/queue_tdd.yml
--- a/.github/workflows/queue_tdd.yml
+++ b/.github/workflows/queue_tdd.yml
@@ -20,9 +20,24 @@ jobs:
 
     - name: Install dependencies
       run: |
-       python -m pip install --upgrade pip
-       pip install pytest pytest-cov pytest_bdd
+        python -m pip install --upgrade pip
+        pip install pytest pytest-cov pytest_bdd flake8
 
-    - name: Run Tests with coverage
-      run: pytest --cov
-    
+    - name: Lint with flake8
+      run: |
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Test with pytest
+      run: |
+        python -m pytest --verbose --junit-xml=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
